"""add chat summary

Revision ID: cda9f323e047
Revises: bee2f76caceb
Create Date: 2026-08-12 21:22:51.396061

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cda9f323e047"
down_revision: Union[str, Sequence[str], None] = "bee2f76caceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chats", sa.Column("summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "summary")
    # ### end Alembic commands ###
